### ISSUE TITLE
Building with Node v12

### ISSUE THREAD

**Issue by atwright147** [myfreeweb/exiv2node#3]
Hey,

It's been a while :)

I am trying to restart my project using this package but I am unable to get it to build with Node v12. I have no experience with either Nan or C(++).

So, I was wondering if you could help me out by pointing me in the right direction to getting this to work? What do I need to change etc :)

With the following `package.json` and the following terminal commands:

```json
{
  "name": "test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "exiv2": "atwright147/exiv2node"
  },
  "devDependencies": {
    "nan": "^2.14.0"
  }
}
```

```sh
npm i --ignore-scripts
npm rebuild
```

<details>
<summary>I get this output</summary>
<div class="highlight highlight-source-shell">
<pre>
> exiv2@0.6.3 install /Users/andy/Development/image-browser/node_modules/exiv2
> node-gyp rebuild

  CXX(target) Release/obj.target/exiv2/exiv2node.o
../exiv2node.cc:103:15: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
        hash->Set(
              ^
/Users/andy/Library/Caches/node-gyp/12.9.0/include/node/v8.h:3371:3: note: 'Set' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/andy/Library/Caches/node-gyp/12.9.0/include/node/v8config.h:311:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../exiv2node.cc:112:15: warning: 'Call' is deprecated [-Wdeprecated-declarations]
    callback->Call(2, argv);
              ^
../../nan/nan.h:1739:3: note: 'Call' has been explicitly marked deprecated here
  NAN_DEPRECATED inline v8::Local<v8::Value>
  ^
../../nan/nan.h:104:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
../exiv2node.cc:128:34: error: no matching member function for call to 'ToObject'
    Local<Object> buf = info[0]->ToObject();
                        ~~~~~~~~~^~~~~~~~
/Users/andy/Library/Caches/node-gyp/12.9.0/include/node/v8.h:2545:44: note: candidate function not viable: requires single argument 'context', but no
      arguments were provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Object> ToObject(
                                           ^
/Users/andy/Library/Caches/node-gyp/12.9.0/include/node/v8.h:2559:31: note: candidate function not viable: requires single argument 'isolate', but no
      arguments were provided
                Local<Object> ToObject(Isolate* isolate) const);
                              ^
../exiv2node.cc:194:15: warning: 'Call' is deprecated [-Wdeprecated-declarations]
    callback->Call(1, argv);
              ^
../../nan/nan.h:1739:3: note: 'Call' has been explicitly marked deprecated here
  NAN_DEPRECATED inline v8::Local<v8::Value>
  ^
../../nan/nan.h:104:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
../exiv2node.cc:213:34: error: no matching member function for call to 'ToObject'
    Local<Object> buf = info[0]->ToObject();
                        ~~~~~~~~~^~~~~~~~
/Users/andy/Library/Caches/node-gyp/12.9.0/include/node/v8.h:2545:44: note: candidate function not viable: requires single argument 'context', but no
      arguments were provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Object> ToObject(
                                           ^
/Users/andy/Library/Caches/node-gyp/12.9.0/include/node/v8.h:2559:31: note: candidate function not viable: requires single argument 'isolate', but no
      arguments were provided
                Local<Object> ToObject(Isolate* isolate) const);
                              ^
../exiv2node.cc:220:30: warning: 'Get' is deprecated: Use maybe version [-Wdeprecated-declarations]
    Local<Value> key = keys->Get(i);
                             ^
/Users/andy/Library/Caches/node-gyp/12.9.0/include/node/v8.h:3429:3: note: 'Get' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version", Local<Value> Get(uint32_t index));
  ^
/Users/andy/Library/Caches/node-gyp/12.9.0/include/node/v8config.h:311:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../exiv2node.cc:223:30: warning: 'Get' is deprecated: Use maybe version [-Wdeprecated-declarations]
      *Nan::Utf8String(tags->Get(key))
                             ^
/Users/andy/Library/Caches/node-gyp/12.9.0/include/node/v8.h:3425:3: note: 'Get' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version", Local<Value> Get(Local<Value> key));
  ^
/Users/andy/Library/Caches/node-gyp/12.9.0/include/node/v8config.h:311:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../exiv2node.cc:297:15: warning: 'Call' is deprecated [-Wdeprecated-declarations]
    callback->Call(1, argv);
              ^
../../nan/nan.h:1739:3: note: 'Call' has been explicitly marked deprecated here
  NAN_DEPRECATED inline v8::Local<v8::Value>
  ^
../../nan/nan.h:104:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
../exiv2node.cc:316:34: error: no matching member function for call to 'ToObject'
    Local<Object> buf = info[0]->ToObject();
                        ~~~~~~~~~^~~~~~~~
/Users/andy/Library/Caches/node-gyp/12.9.0/include/node/v8.h:2545:44: note: candidate function not viable: requires single argument 'context', but no
      arguments were provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Object> ToObject(
                                           ^
/Users/andy/Library/Caches/node-gyp/12.9.0/include/node/v8.h:2559:31: note: candidate function not viable: requires single argument 'isolate', but no
      arguments were provided
                Local<Object> ToObject(Isolate* isolate) const);
                              ^
../exiv2node.cc:322:34: warning: 'Get' is deprecated: Use maybe version [-Wdeprecated-declarations]
    Local<v8::Value> key = keys->Get(i);
                                 ^
/Users/andy/Library/Caches/node-gyp/12.9.0/include/node/v8.h:3429:3: note: 'Get' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version", Local<Value> Get(uint32_t index));
  ^
/Users/andy/Library/Caches/node-gyp/12.9.0/include/node/v8config.h:311:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../exiv2node.cc:376:18: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
        preview->Set(Nan::New<String>("mimeType").ToLocalChecked(), Nan::New<String>(previews[i].mimeType.c_str()).ToLocalChecked());
                 ^
/Users/andy/Library/Caches/node-gyp/12.9.0/include/node/v8.h:3371:3: note: 'Set' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/andy/Library/Caches/node-gyp/12.9.0/include/node/v8config.h:311:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../exiv2node.cc:377:18: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
        preview->Set(Nan::New<String>("height").ToLocalChecked(), Nan::New<Number>(previews[i].height));
                 ^
/Users/andy/Library/Caches/node-gyp/12.9.0/include/node/v8.h:3371:3: note: 'Set' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/andy/Library/Caches/node-gyp/12.9.0/include/node/v8config.h:311:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../exiv2node.cc:378:18: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
        preview->Set(Nan::New<String>("width").ToLocalChecked(), Nan::New<Number>(previews[i].width));
                 ^
/Users/andy/Library/Caches/node-gyp/12.9.0/include/node/v8.h:3371:3: note: 'Set' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/andy/Library/Caches/node-gyp/12.9.0/include/node/v8config.h:311:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../exiv2node.cc:379:18: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
        preview->Set(Nan::New<String>("data").ToLocalChecked(), Nan::CopyBuffer(previews[i].data, previews[i].size).ToLocalChecked());
                 ^
/Users/andy/Library/Caches/node-gyp/12.9.0/include/node/v8.h:3371:3: note: 'Set' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/andy/Library/Caches/node-gyp/12.9.0/include/node/v8config.h:311:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../exiv2node.cc:381:16: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
        array->Set(i, preview);
               ^
/Users/andy/Library/Caches/node-gyp/12.9.0/include/node/v8.h:3380:3: note: 'Set' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/andy/Library/Caches/node-gyp/12.9.0/include/node/v8config.h:311:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../exiv2node.cc:387:15: warning: 'Call' is deprecated [-Wdeprecated-declarations]
    callback->Call(2, argv);
              ^
../../nan/nan.h:1739:3: note: 'Call' has been explicitly marked deprecated here
  NAN_DEPRECATED inline v8::Local<v8::Value>
  ^
../../nan/nan.h:104:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
../exiv2node.cc:434:34: error: no matching member function for call to 'ToObject'
    Local<Object> buf = info[0]->ToObject();
                        ~~~~~~~~~^~~~~~~~
/Users/andy/Library/Caches/node-gyp/12.9.0/include/node/v8.h:2545:44: note: candidate function not viable: requires single argument 'context', but no
      arguments were provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Object> ToObject(
                                           ^
/Users/andy/Library/Caches/node-gyp/12.9.0/include/node/v8.h:2559:31: note: candidate function not viable: requires single argument 'isolate', but no
      arguments were provided
                Local<Object> ToObject(Isolate* isolate) const);
                              ^
../exiv2node.cc:442:6: error: variable has incomplete type 'void'
void InitAll(Handle<Object> target) {
     ^
../exiv2node.cc:442:14: error: use of undeclared identifier 'Handle'
void InitAll(Handle<Object> target) {
             ^
../exiv2node.cc:442:21: error: 'Object' does not refer to a value
void InitAll(Handle<Object> target) {
                    ^
/Users/andy/Library/Caches/node-gyp/12.9.0/include/node/v8.h:3369:17: note: declared here
class V8_EXPORT Object : public Value {
                ^
../exiv2node.cc:442:29: error: use of undeclared identifier 'target'
void InitAll(Handle<Object> target) {
                            ^
../exiv2node.cc:442:36: error: expected ';' after top level declarator
void InitAll(Handle<Object> target) {
                                   ^
                                   ;
13 warnings and 9 errors generated.
make: *** [Release/obj.target/exiv2/exiv2node.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/andy/.npm-packages/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:196:23)
gyp ERR! stack     at ChildProcess.emit (events.js:209:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Darwin 18.7.0
gyp ERR! command "/usr/local/bin/node" "/Users/andy/.npm-packages/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/andy/Development/image-browser/node_modules/exiv2
gyp ERR! node -v v12.9.0
gyp ERR! node-gyp -v v5.0.3
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! exiv2@0.6.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the exiv2@0.6.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/andy/.npm/_logs/2019-08-24T16_03_23_239Z-debug.log
zsh: exit 1     npm i
</pre>
</div>
</details>

Many thanks,


Andy

**Comment by valpackett** [comment]
I did a minimal fix. But this code is quite old and really should be rewritten for N-API instead of nan..

**Comment by atwright147** [comment]
You are a legend.

Thank you very much :)
